<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="saroj-HP" name="Default test" tests="3" failures="0" timestamp="2 Mar 2020 17:47:49 GMT" time="33.378" errors="0">
  <testcase name="@AfterClass tearDown" time="0.0" classname="com.tests.CreateAccountPageTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Login - My Store.] but found [Login - My Store]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Login - My Store.] but found [Login - My Store]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.tests.CreateAccountPageTest.tearDown(CreateAccountPageTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:220)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- @AfterClass tearDown -->
  <testcase name="verifyLoginPageTitleTest" time="1.53" classname="com.tests.CreateAccountPageTest"/>
  <testcase name="createAccountTest" time="8.802" classname="com.tests.CreateAccountPageTest"/>
  <testcase name="verifyAccountTest" time="0.171" classname="com.tests.CreateAccountPageTest"/>
</testsuite> <!-- Default test -->
